# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-21 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20180920_1515'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectresult',
            unique_together=set([('result', 'subject')]),
        ),
    ]
