# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-21 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20180921_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='subjectresult',
            options={'ordering': ('id',)},
        ),
    ]
