# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-21 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediction', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='profession',
        ),
        migrations.AddField(
            model_name='course',
            name='media',
            field=models.ManyToManyField(to='university.Media'),
        ),
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profession',
            name='media',
            field=models.ManyToManyField(to='university.Media'),
        ),
        migrations.AddField(
            model_name='profession',
            name='personalities',
            field=models.ManyToManyField(to='prediction.Personality'),
        ),
    ]
