# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-21 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20180921_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='media',
            field=models.ManyToManyField(blank=True, null=True, to='university.Media'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='media',
            field=models.ManyToManyField(blank=True, null=True, to='university.Media'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='personalities',
            field=models.ManyToManyField(blank=True, null=True, to='prediction.Personality'),
        ),
    ]
