# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-21 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20180921_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='coursecutoff',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='coursecutoff',
            unique_together=set([('year', 'course')]),
        ),
    ]
